### ISSUE TITLE
Sample Dataset

### ISSUE THREAD

**Issue by Youngjoo-Kim** [cavayangtao/lanoising#1]
Hello,
Thank you so much for your great research and open code!
I have two questions about the dataset and models.
1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
2. Your .m objective-c files are broken for me..... how can i solve this problem?

![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)

I'll wait for your answer.
Thank you!

**Comment by cavayangtao** [comment]
Hi Youngjoo,
Thank you for your interest in our work, and sorry for the very delayed reply.
This work is not under the DENSE project, although we recorded the training data using the same weather chamber as them. Currently, our training data is not released. You can test our models using the EU long-term dataset: https://epan-utbm.github.io/utbm_robocar_dataset/. Actually, our models should work on any rosbag recorded by the Velodyne LiDAR.
I have downloaded and tested all the .m files again, but I didn't find any problem. Please make sure you use the joblib of version 0.14.1 to load the .m files.

Regards,
Tao

**Comment by cavayangtao** [comment]
> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!



> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!



> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!



> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!



> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!

Hi Youngjoo,
Thank you for your interest in our work, and sorry for the very delayed reply.
This work is not under the DENSE project, although we recorded the training data using the same weather chamber as them. Currently, our training data is not released. You can test our models using the EU long-term dataset: https://epan-utbm.github.io/utbm_robocar_dataset/. Actually, our models should work on any rosbag recorded by the Velodyne LiDAR.
I have downloaded and tested all the .m files again, but I didn't find any problem. Please make sure you use the joblib of version 0.14.1 to load the .m files.

Regards,
Tao

**Comment by cavayangtao** [comment]
> Hello,
> Thank you so much for your great research and open code!
> I have two questions about the dataset and models.
> 
> 1. The DENSE dataset is not provided in the form of .bag, is there a way to receive sample data?
> 2. Your .m objective-c files are broken for me..... how can i solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57059989/105346948-9188ac80-5c29-11eb-88d6-e00207ac3e28.png)
> ![image](https://user-images.githubusercontent.com/57059989/105347013-a5341300-5c29-11eb-8063-a5169b928662.png)
> 
> I'll wait for your answer.
> Thank you!

Hi Youngjoo,
Thank you for your interest in our work, and sorry for the very delayed reply.
This work is not under the DENSE project, although we recorded the training data using the same weather chamber as them. Currently, our training data is not released. You can test our models using the EU long-term dataset: https://epan-utbm.github.io/utbm_robocar_dataset/. Actually, our models should work on any rosbag recorded by the Velodyne LiDAR.
I have downloaded and tested all the .m files again, but I didn't find any problem. Please make sure you use the joblib of version 0.14.1 to load the .m files.

Regards,
Tao
