### ISSUE TITLE
Reference rosbag missing

### ISSUE THREAD

**Issue by broughtong** [cavayangtao/lanoising#4]
The reference rosbag "2019-02-19-17-13-37.bag", mentioned in the README, is missing as far as I can tell.

It seems its not in the google drive with the rest of the models, and I cannot find a rosbag with the same name on the EU car dataset website.

**Comment by cavayangtao** [comment]
Hi @broughtong.
sorry for the delayed reply. It's possible to apply the lanoising model to the EU car dataset as follows: 1. play the rosbag in EU car dataset; 2. rosrun nodelet nodelet standalone velodyne_pointcloud/CloudNodelet _calibration:="/opt/ros/kinetic/share/velodyne_pointcloud/params/32db.yaml"; 3. launch lanoising node. You can set disappear_model = 1 in lanoising.py for fast processing.

**Comment by broughtong** [comment]
No problem. Actually, I meant that the reference rosbag titled '2019-02-19-17-13-37.bag' is not in the EU car dataset, I see many others, but not this one :)
